services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,INTERNAL://kafka:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - online_learning_platform_net
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list || exit 1"]
      interval: 15s
      timeout: 20s
      retries: 10
      start_period: 60s

  consul-server:
    image: hashicorp/consul:latest
    container_name: consul-server
    ports:
      - "8500:8500"
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8302:8302/udp"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect=1 -ui -client=0.0.0.0"
    environment:
      CONSUL_HTTP_ADDR: "http://0.0.0.0:8500"
      CONSUL_BIND_INTERFACE: "eth0"
    networks:
      - online_learning_platform_net


  postgres-auth:
    image: postgres:15-alpine
    container_name: postgres-auth
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: ${AUTH_DB_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - online_learning_platform_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USERNAME} -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s


  postgres-users:
    image: postgres:15-alpine
    container_name: postgres-users
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: ${USER_DB_USERNAME}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - online_learning_platform_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_DB_USERNAME} -d user_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s


  postgres-courses:
    image: postgres:15-alpine
    container_name: postgres-courses
    environment:
      POSTGRES_DB: course_db
      POSTGRES_USER: ${COURSE_DB_USERNAME}
      POSTGRES_PASSWORD: ${COURSE_DB_PASSWORD}
    volumes:
      - postgres_courses_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - online_learning_platform_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${COURSE_DB_USERNAME} -d course_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s


  postgres-lessons:
    image: postgres:15-alpine
    container_name: postgres-lessons
    environment:
      POSTGRES_DB: lesson_db
      POSTGRES_USER: ${LESSON_DB_USERNAME}
      POSTGRES_PASSWORD: ${LESSON_DB_PASSWORD}
    volumes:
      - postgres_lessons_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - online_learning_platform_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${LESSON_DB_USERNAME} -d lesson_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s

  
  postgres-enrollments:
    image: postgres:15-alpine
    container_name: postgres-enrollments
    environment:
      POSTGRES_DB: enrollment_db
      POSTGRES_USER: ${ENROLLMENT_DB_USERNAME}
      POSTGRES_PASSWORD: ${ENROLLMENT_DB_PASSWORD}
    volumes:
      - postgres_enrollments_data:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    networks:
      - online_learning_platform_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ENROLLMENT_DB_USERNAME} -d enrollment_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s


  redis-auth:
    image: redis:7-alpine
    container_name: redis-auth
    ports:
      - "6380:6379"
    volumes:
      - redis_auth_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      start_period: 60s
    networks:
      - online_learning_platform_net


  redis-users:
    image: redis:7-alpine
    container_name: redis-users
    ports:
      - "6381:6379"
    volumes:
      - redis_users_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      start_period: 60s
    networks:
      - online_learning_platform_net
  

  redis-courses:
    image: redis:7-alpine
    container_name: redis-courses
    ports:
      - "6382:6379"
    volumes:
      - redis_courses_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      start_period: 60s
    networks:
      - online_learning_platform_net


  redis-lessons:
    image: redis:7-alpine
    container_name: redis-lessons
    ports:
      - "6383:6379"
    volumes:
      - redis_lessons_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      start_period: 60s
    networks:
      - online_learning_platform_net

  
  redis-enrollments:
    image: redis:7-alpine
    container_name: redis-enrollments
    ports:
      - "6384:6379"
    volumes:
      - redis_enrollments_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      start_period: 60s
    networks:
      - online_learning_platform_net

  
  config-server:
    build: 
      context: ../backend/online-learning-platform-config-server
    ports:
      - "8888:8888"
    environment:
       - GIT_USERNAME=${GIT_USERNAME}
       - GIT_PASSWORD=${GIT_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8888/actuator/health"]
      interval: 15s
      timeout: 5s
      start_period: 90s
    restart: unless-stopped
    networks:
      - online_learning_platform_net


  gateway-service:
    build:
      context: ../backend/online-learning-platform-gateway-service
    ports:
      - "8080:8080"
    environment:
    - JWT_SECRET=${JWT_SECRET}
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8080/internal/actuator/health"]
      interval: 15s
      timeout: 5s
      start_period: 60s
    depends_on:
      config-server:
        condition: service_healthy
      consul-server:
        condition: service_started
    restart: unless-stopped
    networks:
      - online_learning_platform_net
    

  auth-service:
    build:
      context: ../backend/online-learning-platform-auth-service
    ports:
      - "8081:8081"
      - "9091:9091"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - AUTH_DB_URL=${AUTH_DB_URL}
      - AUTH_DB_USERNAME=${AUTH_DB_USERNAME}
      - AUTH_DB_PASSWORD=${AUTH_DB_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_LOCATIONS=classpath:/db/migration
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_EMAIL_ADDRESS={ADMIN_EMAIL_ADDRESS}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - KAFKA_CONSUMER_GROUP_ID=auth-service
      - KAFKA_AUTO_OFFSET_RESET=earliest
    volumes:
      - ../backend/online-learning-platform-auth-service/src/main/resources/db/migration:/app/resources/db/migration
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8081/internal/actuator/health"]
      interval: 15s
      timeout: 5s
      start_period: 60s
    depends_on:
      config-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      consul-server:
        condition: service_started
      redis-auth:
        condition: service_healthy
      postgres-auth:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - online_learning_platform_net

  
  user-service:
    build:
      context: ../backend/online-learning-platform-user-service
    ports:
      - "8082:8082"
      - "9093:9093"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - USER_DB_URL=${USER_DB_URL}
      - USER_DB_USERNAME=${USER_DB_USERNAME}
      - USER_DB_PASSWORD=${USER_DB_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_LOCATIONS=classpath:/db/migration
      - KAFKA_CONSUMER_GROUP_ID=user-service
      - KAFKA_AUTO_OFFSET_RESET=earliest
    volumes:
      - ../backend/online-learning-platform-user-service/src/main/resources/db/migration:/app/resources/db/migration
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8082/internal/actuator/health"]
      interval: 15s
      timeout: 5s
      start_period: 60s
    depends_on:
      config-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      consul-server:
        condition: service_started
      redis-users:
        condition: service_healthy
      postgres-users:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - online_learning_platform_net
      

  course-service:
    build:
      context: ../backend/online-learning-platform-course-service
    ports:
      - "8083:8083"
      - "9095:9095"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - COURSE_DB_URL=${COURSE_DB_URL}
      - COURSE_DB_USERNAME=${COURSE_DB_USERNAME}
      - COURSE_DB_PASSWORD=${COURSE_DB_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_LOCATIONS=classpath:/db/migration
    volumes:
      - ../backend/online-learning-platform-course-service/src/main/resources/db/migration:/app/resources/db/migration
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8083/internal/actuator/health"]
      interval: 15s
      timeout: 5s
      start_period: 60s
    depends_on:
      config-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      consul-server:
        condition: service_started
      redis-courses:
        condition: service_healthy
      postgres-courses:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - online_learning_platform_net

  
  lesson-service:
    build:
      context: ../backend/online-learning-platform-lesson-service
    ports:
      - "8084:8084"
      - "9097:9097"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - LESSON_DB_URL=${LESSON_DB_URL}
      - LESSON_DB_USERNAME=${LESSON_DB_USERNAME}
      - LESSON_DB_PASSWORD=${LESSON_DB_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_LOCATIONS=classpath:/db/migration
    volumes:
      - ../backend/online-learning-platform-lesson-service/src/main/resources/db/migration:/app/resources/db/migration
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8084/internal/actuator/health"]
      interval: 15s
      timeout: 5s
      start_period: 60s
    depends_on:
      config-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      consul-server:
        condition: service_started
      redis-lessons:
        condition: service_healthy
      postgres-lessons:
        condition: service_healthy
    networks:
      - online_learning_platform_net


  enrollment-service:
    build:
      context: ../backend/online-learning-platform-enrollment-service
    ports:
      - "8085:8085"
      - "9099:9099"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - ENROLLMENT_DB_URL=${ENROLLMENT_DB_URL}
      - ENROLLMENT_DB_USERNAME=${ENROLLMENT_DB_USERNAME}
      - ENROLLMENT_DB_PASSWORD=${ENROLLMENT_DB_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_LOCATIONS=classpath:/db/migration
    volumes:
      - ../backend/online-learning-platform-enrollment-service/src/main/resources/db/migration:/app/resources/db/migration
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8085/internal/actuator/health"]
      interval: 15s
      timeout: 5s
      start_period: 60s
    depends_on:
      config-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      consul-server:
        condition: service_started
      redis-enrollments:
        condition: service_healthy
      postgres-enrollments:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - online_learning_platform_net


  notification-service:
    ports:
      - "8086:8086"
    build:
      context: ../backend/online-learning-platform-notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - KAFKA_CONSUMER_GROUP_ID=notification-service
      - KAFKA_AUTO_OFFSET_RESET=earliest
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8086/internal/actuator/health"]
      interval: 15s
      timeout: 5s
      start_period: 60s
    depends_on:
      config-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      consul-server:
        condition: service_started
    restart: unless-stopped
    networks:
      - online_learning_platform_net
    

  frontend:
    build: 
      context: ../frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      gateway-service:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
      course-service:
        condition: service_healthy
      lesson-service:
        condition: service_healthy
      enrollment-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - online_learning_platform_net


volumes:
  postgres_auth_data:
  postgres_users_data:
  postgres_courses_data:
  postgres_lessons_data:
  postgres_enrollments_data:

  redis_auth_data:
  redis_users_data:
  redis_courses_data:
  redis_lessons_data:
  redis_enrollments_data:  


networks:
  online_learning_platform_net:
    driver: bridge
